name: yolighttransfer
description: A modern file transfer application with Material You design.
publish_to: 'none'
version: 0.1.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  intl: ^0.18.1
  path_provider: ^2.1.1
  connectivity_plus: ^7.0.0
  fluttertoast: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  file_picker: ^10.3.3
  file_selector: ^1.0.4
  permission_handler: ^12.0.1
  crypto: ^3.0.3
  http: ^1.1.0
  yaml: ^3.1.2
  flutter_markdown: ^0.6.18
  flutter_local_notifications: ^17.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  charset: ^2.0.1
  tflite_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.10.0
  mocktail: ^1.0.0

msix_config:
  display_name: YoLightTransfer
  publisher_display_name: WaveYo
  identity_name: com.waveyo.yolighttransfer
  msix_version: 0.1.2.0
  certificate_path: 
  certificate_password: 
  logo_path: 
  start_menu_icon_path: 
  tile_icon_path: 
  capabilities: internetClient,privateNetworkClientServer
  file_extension:

flutter:
  uses-material-design: true

  assets:
    - assets/front/MiSans-Regular.ttf
    - lib/config.yaml
    - assets/models/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/front/MiSans-Regular.ttf
